# use ${VARIABLE} for interpolating environment variables
mysql:
  host: 127.0.0.1
  port: 3306
  database: amethyst_model_test
  username: amethyst_model
  password: ${DB_PASS} 

sqlite:
  database: config/test.db

postgresql:
  host: 127.0.0.1
  port: 5432
  database: amethyst_model_test
  username: drujensen
  password: ${DB_PASS} 

